      SUBROUTINE UTRS(SHIFT,TEMP,DTEMP,TIME,DTIME,PREDEF,DPRED,STATEV,
     1CMNAME,COORDS)
C
C
      INCLUDE 'ABA_PARAM.INC'
C
      DIMENSION TIME(2)
      DIMENSION PREDEF(1),DPRED(1),STATEV(1),COORDS(1),SHIFT(2)
      CHARACTER*80 CMNAME
      DATA ALN10,TOL,HTOL/2.302585093,1.E-10,1.E-7/
      DATA T0,C1,C2,TWO,AFc/295.15,17.4,66.35,2.,24000.0/
C
      TREL0 = TEMP - DTEMP - T0
      TREL1 = TEMP - T0
C
      A0 = AFc*(1/(TEMP-DTEMP) - 1/(T0))
      A1 = AFc*(1/(TEMP) - 1/(T0))
      H0 = -ALN10*C1*TREL0/(C2+TREL0)
      H1 = -ALN10*C1*TREL1/(C2+TREL1)
c     
      IF (TEMP .LE. T0) THEN
        SHIFT(1) = EXP(A0)
        SHIFT(2) = EXP(A1)
      ELSE
        SHIFT(1) = EXP(H0)
        SHIFT(2) = EXP(H1)
      END IF
C
      RETURN
      END

      SUBROUTINE UEXPAN(EXPAN,DEXPANDT,TEMP,TIME,DTIME,PREDEF,DPRED,
     1     STATEV,CMNAME,NSTATV,NOEL)

      IMPLICIT REAL*8 (A-H,O-Z)

      DIMENSION EXPAN(*),DEXPANDT(*),TEMP(2),TIME(2),PREDEF(*),
     1     DPRED(*),STATEV(NSTATV)

      REAL*8 ALPHA

      ALPHA1 = 0.00023
      ALPHA2 = 0.0006734545454545454
	  ALPHA = 0.0D0

      IF (TEMP(2) .LE. 0.0) THEN
		 ALPHA = ALPHA1
      ELSE
		 ALPHA = ALPHA2
      END IF
	  EXPAN(1) = ALPHA * TEMP(2)
	  DEXPANDT(1) = 0.0

      RETURN
      END